#!/bin/sh

# Keep everything up to date!
# This crontab is part of the notifiarr-worker package.

DEBIAN_FRONTEND=noninteractive
LOGDIR="/var/log/apt-output"

mkdir -p "${LOGDIR}"

/usr/bin/apt update > "${LOGDIR}/update.log" 2>&1
/usr/bin/apt upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" > "${LOGDIR}/upgrade.log" 2>&1
