name: build-and-release
on:
  push:
    branches:
      - unstable
      - main
    tags:
      - v*
  pull_request:
    branches:
    - main
    - unstable
permissions:
  contents: read
jobs:
  release:
    # description: "Builds all the Notifiarr client binaries and packages for a release."
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/unstable' || github.ref == 'refs/heads/main'
    outputs:
      version: ${{ steps.release.outputs.version }}
    name: Make Release Assets
    runs-on: ubuntu-latest
    env:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          # we need the whole thing so we can count commits.
          fetch-depth: '0'
      - name: make-release
        id: release
        run: |
          sudo apt install -y fakeroot zip debsigs gnupg jq 
          sudo gem install --no-document fpm
          echo "${GPG_SIGNING_KEY}" | gpg --import -
          bash build.sh
          mkdir release
          mv *.deb release
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release

  deploy-nonpublic-packagecloud:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: release
    name: Deploy Nonpublic PackageCloud
    runs-on: ubuntu-latest
    steps:
      - name: Download release files
        uses: actions/download-artifact@v4
        with:
          name: release
      - uses: golift/upload-packagecloud@v1.1
        with:
          userrepo: golift/nonpublic
          apitoken: ${{ secrets.PACKAGECLOUD_TOKEN }}
          packages: .
          debdists: ubuntu/focal